spring:
  application:
    name: Artifact
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/database/dev_db
    #jdbc:h2:file:~/database/test29
    #jdbc:h2:tcp://localhost/~/database/test29 // ?? ??
    username: sa
    password:
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 Dialect ?? ??
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

## ?? ??
logging:
  level:
    com.ll.demo03: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE